JuliaDebug/Debugger.jl

- src/Debugger.jl
- src/DebuggerFramework.jl
- src/LineNumbers.jl
- src/commands.jl
- src/operations.jl
- src/printing.jl
- test/evaling.jl
- test/misc.jl
- test/runtests.jl
- test/stepping.jl
- test/ui.jl
- test/utils.jl
DebuggerFramework is an API created to facilitate writing REPL debugger interfaces by overloading a few functions. Debugger.jl is the only working consumer of that API (and likely will continue to be so).
Since there is only one package using the API (and in fact that package bundles it) there is not really any point keeping the abstraction since it just makes things less flexible.
This PR therefore gets rid of DebuggerFramework in favour of normal methods.
> Remove DebuggerFramework abstraction

- src/Debugger.jl
I inadvertently led to the introduction of this typo in [this conversation](https://github.com/JuliaDebug/Debugger.jl/pull/13#discussion_r258071442). This PR fixes that.
> Debugger.jl: fix duplicated word in comment

- src/operations.jl
Original:
```
3   │   %3 = ($(QuoteNode(Branch)))($(QuoteNode(LinearAlgebra.det)), %1, %2)
```
Before this PR:
```
3   │   %3 = (Branch)))($(QuoteNode(LinearAlgebra.det, %1, %2)
```
After this PR:
```
3   │   %3 = (Branch)(LinearAlgebra.det, %1, %2)
```
> fix regex for quotenode removal

- README.md
- src/commands.jl
Fix #15.
Also remove period at end of preceding item, to match other items.
> Document  command.

- src/commands.jl
- test/stepping.jl
Fixes #34 
Might also want to make sure we are not modifying locals in `eval_code` but that is much harder. It would also not make the interpreter itself crash, just give weird execution.
> prevent stepping in non toplevel frames

- src/Debugger.jl
- src/commands.jl
- src/printing.jl
- src/repl.jl
- test/evaling.jl
- test/misc.jl
- test/stepping.jl
- test/utils.jl
Should make the code structurally a bit more similar to how things will be with the linked list stuff.
> get rid of explicit frame command to execute_command

- src/Debugger.jl
- src/printing.jl
- test/misc.jl
This showed up while mixing `nc` and `s` with default- and keyword-argument methods.
> Avoid attempt to print `nothing` when stepping

- src/commands.jl
- test/ui.jl
- test/ui/history_gcd.multiout
Fixes #92 and fixes https://github.com/JuliaDebug/Debugger.jl/issues/91
This puts a bit of source code from Base into the tests but that part hasnt been touched for years so should be ok.
> fix f and fr

- README.md
- src/commands.jl
- test/ui.jl
- test/ui/history_gcd.multiout
```
julia> @run f()
Breaking for error:
ERROR: StringIndexError("αβ", 2)
In string_index_err(s, i) at strings/string.jl
>12  @noinline string_index_err(s::AbstractString, i::Integer) =
13      throw(StringIndexError(s, Int(i)))
14
15  const ByteArray = Union{Vector{UInt8},Vector{Int8}}
16
About to run: (throw)(StringIndexError("αβ", 2))
1|debug>
```
Fixes https://github.com/JuliaDebug/Debugger.jl/issues/95
> improve breakpoint printing

- Manifest.toml
- Project.toml
- src/Debugger.jl
- src/printing.jl
- test/ui.jl
- test/ui/history_kw.multiout
Quite ugly but seems to work:
```
julia> @enter g(1,2,3)
In g(x, y, z) at REPL[16]
>1  g(x,y,z) = f(x; y=y, z=z)
About to run: (f)(1; y=2, z=3)
```
Needs tests
Fixes #107
> fix showing keyword calls

- src/LineNumbers.jl
- src/printing.jl
Seems to happen in Juno for some reason (https://discourse.julialang.org/t/new-debugger/21974/14). Will try figure out the root cause.
> protect against files being out of sync with lineinfo in the method

- README.md
- src/commands.jl
- src/repl.jl
Fixes half of #140. @Keno, I'm having troubles reproducing the problem with the evaluation in the wrong level. For example:
```jl
julia> function f(x)
x = 1
g(x)
end
f (generic function with 1 method)
julia> function g(z)
y = 4
return z
end
g (generic function with 1 method)
julia> @enter f(3)
In f(x) at REPL[24]:2
2     x = 1
>3     g(x)
4  end
About to run: (g)(1)
1|debug> s
In g(z) at REPL[25]:2
>2      y = 4
3      return z
4  end
About to run: 4
1|debug> f 2 # at frame 2
In f(x) at REPL[24]:2
2     x = 1
>3     g(x)
4  end
About to run: (g)(1)
2|julia> x 
1
2|debug> f 1
In g(z) at REPL[25]:2
>2      y = 4
3      return z
4  end
About to run: 4
1|julia> x
ERROR: UndefVarError: x not defined
```
> fix printing for evaluation level and make fr show the current level by default instead of level 1

- src/commands.jl
Previously:
```
julia> @enter sin(2.)
In sin(x) at special/trig.jl:30
>30  absx = abs(x)
31  if absx < T(pi)/4 #|x| ~<= pi/4, no need for reduction
32      if absx < sqrt(eps(T))
33          return x
34      end
About to run: (abs)(2.0)
1|debug> so lghfd
ERROR: ArgumentError: command so lghfd not recognized
julia> 
```
> prevent erroring out of debugger if we add an argument to one of the JuliaInterpreter commands

- src/Debugger.jl
Not the best error message but it is better than status quo
Closes https://github.com/JuliaDebug/Debugger.jl/issues/150
> add an error message if trying to enter a compiled function

- Manifest.toml
- src/commands.jl
- src/repl.jl
- test/ui.jl
- test/ui/history_break_error.multiout
Need to figure out how to deal with the absolute paths in the stacktrace when breaking on error. There isn't really a nice way to change this.
Fixes #145
> WIP: show a nice stacktrace when breaking on error

- Project.toml
- REQUIRE
- reexport some more breakpoint functionality (#133) 
- fix printing for the current evaluation level (#142)
- make fr show the current level by default instead of level 1 (#142)
- prevent erroring out of debugger on bad input commands  (#143)
- use Base.error_color() in error messages to be consistent with Base for errors (#144) 
- show an error message on empty first command (#149) 
- add an error message if trying to `@enter` a compiled function (#151) 
- show a stacktrace when breaking on error (#147) 
- add error message when using the macros on invalid expressions
> prepare for new release

- .travis.yml
- Manifest.toml
- src/locationinfo.jl
This is what you get now @staticfloat 
```jl
julia> @enter back(1f0)
In #71(Δ) at C:\Users\Kristoffer\.julia\packages\Zygote\mlF4T\src\compiler\interface.jl:38
>38  y, Δ -> tailmemaybe(back(Δ))
About to run: (getfield)(<suppressed 119 bytes of output>, :back)
1|debug> si
In #71(Δ) at C:\Users\Kristoffer\.julia\packages\Zygote\mlF4T\src\compiler\interface.jl:38
>38  y, Δ -> tailmemaybe(back(Δ))
About to run: (∂(getfield(Main, Symbol("##5#6"))()))(1.0f0)
1|debug> 
In Pullback(Δ) at C:\Users\Kristoffer\.julia\packages\Zygote\mlF4T\src\compiler\interface2.jl:16
>1  1 ─      $(Expr(:meta, :inline))
2  │   %2 = (getfield)(#self#, :t)
3  │   %3 = (getindex)(%2, 1)
4  │   %4 = (%3)(Δ)
5  │   %5 = (Zygote.gradindex)(%4, 2)
About to run: $(Expr(:meta, :inline))
1|debug> 
In Pullback(Δ) at …
```
> fix for bad line info for certain statements

- Manifest.toml
- Project.toml
- REQUIRE
- src/commands.jl
Needs a new tag of JuliaInterpreter
- fix for bad line info for certain statements  (#158)
- use CodeTracking for source lookup (#160) 
- make robust against failures in code highlighting (#164) 
- fix printing for calling Core._apply (#166) 
-  implement `until` (#169) 
- add a shortcut to change the number of source code shown (#171)
> release 0.4.0

- Project.toml
- Add a breakpoint UI (#181)
- Bugfix with lowered code printing on on JuliaInterpreter 0.5.1 (#182)
- Add `up`/`down` commands to navigate the call stack (#178)
Needs a new tag for JuliaInterpreter.
> Release 0.5.0

- README.md
- src/commands.jl
Additional backtick causing incorrect colors in terminal when in help mode.
> Remove additional backtick

- README.md
I was about to request a functionality similar to the `keyboard` function in Matlab. Turns out it's already there, so here's a doc PR instead.
> Document `@bp` macro

- Project.toml
- src/printing.jl
Supersedes https://github.com/JuliaDebug/Debugger.jl/pull/87.
[MonokaiMini](https://github.com/JuliaDocs/Highlights.jl/pull/36) is a theme that should at least be readable on most terminal backgrounds, and seems like a better default than Monokai.
> use MonokaiMini theme

- src/Debugger.jl
- src/repl.jl
- test/ui.jl
Enables local completions in `julia_prompt`
> Local completions

- src/Debugger.jl
- src/breakpoints.jl
- test/misc.jl
```
julia> @enter collect(combinations(1:3,2))
In collect(itr) at array.jl:558
>558  collect(itr) = _collect(1:1 #= Array =#, itr, IteratorEltype(itr), IteratorSize(itr))
About to run: (Colon())(1, 1)
1|debug> bp add Base.iterate(itr)
[ Info: added breakpoint for method iterate(::Combinatorics.Combinations{UnitRange{Int64}})
1] iterate(::Combinatorics.Combinations{UnitRange{Int64}})
1|debug> bp add Base.iterate(::Combinatorics.Combinations)
[ Info: added breakpoint for method iterate(::Combinatorics.Combinations)
1] iterate(::Combinatorics.Combinations{UnitRange{Int64}})
2] iterate(::Combinatorics.Combinations)
1|debug> bp add Base.iterate(::Combinatorics.Combinations{UnitRange{Int64}})
[ Info: added breakpoint for method iterate(::Combinatorics.Combinations{UnitRange{Int64}})
1] …
```
> Some breakpoint fixes

- src/Debugger.jl
- test/misc.jl
close #222 
It works, but strangely the closing bracket is missing in this example:
```julia
julia> @enter exp.(1 .+ 2)
In ##thunk#381() at REPL[24]:1
>1  @enter exp.(1 .+ 2
About to run: (Base.Broadcast.broadcasted)(+, 1, 2)
1|debug>
```
> Automatically wrap code in at-enter/run macros

- README.md
New Julia users may not understand the meaning of ] to enter the
package manager from the Julia REPL. Instead, start with code that
works when they copy and paste.
A debugger was one of the first things I looked for as a new Julia user. I copy pasted `] add Debugger` and got a syntax error. This change avoids that error, slightly lowering the bar to new users.
> Make install code run if users copy and paste

- src/commands.jl
Used regex to eliminate multiple whitespace issue in user input, let me know if anything needs to be changed or added!
> Normalize whitespaces in user input

- src/locationinfo.jl
https://github.com/JuliaDebug/Debugger.jl/commit/183c5b4eaebf2ef20d84457b1862fecbe6fb3a1e#r67187294
> fix `defline` when method start is unknown

- src/breakpoints.jl
- test/misc.jl
Fixes https://github.com/JuliaDebug/Debugger.jl/issues/311
Requires https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/524
> allow breaking on constructors

- Project.toml
- README.md
- src/commands.jl
See https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/558.
> Add :sr command to step until next return.

- src/repl.jl
Fixes #347
Context: https://github.com/JuliaLang/julia/pull/54311#issuecomment-2086278926
Packages are now required to add `hint` kwarg. We are defaulting `hint` to `true`.
> update `LineEdit.complete_line` with stdlib repl completion changes

- .github/workflows/CI.yml
- src/repl.jl
Replaces https://github.com/JuliaDebug/Debugger.jl/pull/366
Needs testing @oscardssmith @KristofferC
> Fix print_response hanging on 1.11.5+

- Project.toml
- src/Debugger.jl
- src/commands.jl
- src/repl.jl
- test/misc.jl
This PR should be merged after https://github.com/JuliaDebug/Debugger.jl/pull/369.
> update to JuliaInterpreter v0.10
