JuliaDebug/Debugger.jl

- src/commands.jl
Necessary for https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/32
> More robustly detect when code will run in Compiled() mode

- Manifest.toml
- src/Debugger.jl
- src/DebuggerFramework.jl
Also fixes a bug when throwing error from the julia evaluate mode.
> fix tests on master

- src/repl.jl
> fix tab completion

- Manifest.toml
- src/Debugger.jl
- src/commands.jl
- src/operations.jl
- src/repl.jl
- test/misc.jl
- test/runtests.jl
- test/stepping.jl
- test/ui.jl
- test/utils.jl
Fixes #29 
Requires https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/86/files
> invert the stack and move something over from JuliaInterpreter

- src/repl.jl
- test/evaling.jl
- test/runtests.jl
Also run the `evaling.jl` test file which was not tested anymore during the refactoring.
Fixes #20
> fix eval code in kwarg functions

- Manifest.toml
- src/printing.jl
- src/repl.jl
- test/evaling.jl
https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/54
> use JuliaInterpreter's Variable struct to implement the printing

- src/Debugger.jl
> fix thingy again

- src/commands.jl
Closes #14. Can be put back on request.
> remove code_typed command

- src/LineNumbers.jl
Not sure how to test it but confirmed locally to work.
Fixes #62
> fix encountering empty line in source (last line?`)

- README.md
- src/commands.jl
> add status command

- Manifest.toml
- Project.toml
- src/commands.jl
- src/locationinfo.jl
- test/misc.jl
> Fix file we look for source code in

- src/printing.jl
- test/ui/history_gcd.multiout
Fixes https://github.com/JuliaDebug/Debugger.jl/issues/80
> account for indentation

- README.md
- src/Debugger.jl
- src/commands.jl
- src/printing.jl
- src/repl.jl
- src/watch.jl
- test/ui.jl
- test/ui/history_gcd.multiout
Fixes https://github.com/JuliaDebug/Debugger.jl/issues/45
> add support for watchers

- src/printing.jl
- test/ui/history_gcd.multiout
> show a token for current line

- README.md
- src/Debugger.jl
Fixes https://github.com/JuliaDebug/Debugger.jl/issues/83
> use the exported break_on from JuliaInterpreter

- README.md
- src/Debugger.jl
- src/commands.jl
- src/printing.jl
- src/repl.jl
- test/ui.jl
- test/ui/history_gcd.multiout
- test/ui/history_noinfo.multiout
- test/utils.jl
> add a toggle for showing lowered code and refactor printing a bit

- src/commands.jl
- src/locationinfo.jl
- src/printing.jl
- test/ui/history_gcd.multiout
> fix line info printing in bt

- src/repl.jl
> improve error message when julia repl is not loaded

- src/Debugger.jl
- src/printing.jl
- src/repl.jl
- src/watch.jl
- test/evaling.jl
> fix evals when the value is a symbols

- src/commands.jl
- test/ui/history_gcd.multiout
Fixes https://github.com/JuliaDebug/Debugger.jl/issues/130
> fix fr showing the correct frame

- README.md
- src/repl.jl
> show an error message on empty first command

- src/Debugger.jl
- test/misc.jl
> add error message when using the macros on invalid expressions

- src/printing.jl
- test/misc.jl
https://github.com/JuliaDocs/Highlights.jl/issues/24
> make robust against failures in code highlighting

- Manifest.toml
- src/locationinfo.jl
- src/printing.jl
- test/misc.jl
- test/ui/history_floor.multiout
- test/ui/history_gcd.multiout
- test/ui/history_kw.multiout
Putting it up here so I don't lose it.
Closes https://github.com/JuliaDebug/Debugger.jl/issues/159
> WIP: use CodeTracking for source lookup

- Manifest.toml
- README.md
- src/commands.jl
- test/stepping.jl
- test/ui.jl
- test/ui/history_until.multiout
Closes https://github.com/JuliaDebug/Debugger.jl/issues/138
> Implement "until!

- README.md
- src/commands.jl
- src/repl.jl
- test/ui.jl
- test/ui/history_until.multiout
Closes https://github.com/JuliaDebug/Debugger.jl/issues/135
> add a shortcut to change the number of source code shown

- README.md
- src/commands.jl
- test/ui.jl
- test/ui/history_updown.multiout
> add up/down commands

- Manifest.toml
- README.md
- src/Debugger.jl
- src/breakpoints.jl
- src/commands.jl
- src/repl.jl
- src/watches.jl
- test/misc.jl
- test/runtests.jl
- test/ui.jl
- test/ui/bp_ui.multiout
Fixes #28 
Requires: https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/259
> Add a breakpoint UI

- src/repl.jl
- test/evaling.jl
Fixes #188. This should be correct, I think.
> fix eval_code for multiple statements on line

- src/breakpoints.jl
- test/misc.jl
- test/stepping.jl
> Breakpoint fixes

- Manifest.toml
- src/printing.jl
- test/ui.jl
- test/ui/history_gcd_1.3.multiout
Fixes https://github.com/JuliaDebug/Debugger.jl/issues/187.
> fixes for changes on Julia master

- src/locationinfo.jl
- test/ui/history_kw.multiout
> fix printing of methods when they have keywords

- Manifest.toml
- src/printing.jl
- test/misc.jl
> Fix lowered printing and update stuff for new Highlights.jl

- src/Debugger.jl
- src/limitio.jl
- src/printing.jl
- test/ui.jl
- test/ui/big_repr_ui.multiout
this helps with delay when the debugger tries to show many large values
Fixes #236
> make a custom io that throws when too much been written to it

- README.md
- src/commands.jl
Includes how one exits eval mode. Fixes #253.
> Expand documentation for eval mode

- README.md
This is a follow up on @timholy's suggestion in #260.
It's basically the same boilerplate install instructions as Revise.jl
> Link to Pkg documentation in Install section

- Project.toml
Requires https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/407
> allow CodeTracking v1.0

- src/printing.jl
- test/ui/history_noinfo.multiout
- test/utils.jl
Should fix https://github.com/JuliaDebug/Debugger.jl/issues/288.
> Filter invalid characters in repr_limited

- Project.toml
- src/printing.jl
Fixes https://github.com/JuliaDebug/Debugger.jl/issues/299.
> compat: JuliaInterpreter 0.9

- README.md
- src/commands.jl
Requires https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/520
> add support for stepping into the last line of a call

- src/printing.jl
Edit: Fixes the keyword argument part of #270 I think.
> Fix printing of kwcalls

- src/repl.jl
Fixes https://github.com/JuliaDebug/Debugger.jl/issues/356.
> improve REPL completion for locals
